apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: thumbapi
          image: docker.io/library/thumbify_api:2.0.0
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: "redis.api-ns.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: config-volume
              mountPath: /configs/
            - name: secret-volume
              mountPath: /secrets/
            - name: uploads
              mountPath: /uploads
      volumes:
        - name: config-volume
          configMap:
            name: api-config
        - name: secret-volume
          secret:
            secretName: apisecrets
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-claim
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: "TCP"
      name: http
      port: 80
      targetPort: 80
