apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: {{ .Values.namespace }}
data:
  API_HOST: "0.0.0.0"
  API_PORT: "3000"
  API_HOST_PORT: "3000"
---
apiVersion: v1
kind: Secret
metadata:
  name: apisecrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB_NUMBER: "0"
  REDIS_PASSWORD: "secret"
  BUCKET_NAME: thumbifybucket
  BUCKET_ACCESS_KEY: s3user
  BUCKET_SECRET_KEY: s3password
  BUCKET_ENDPOINT: http://bucket:9000
